services:
  postgres:
    image: postgres
    container_name: pedidos-backend
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres