FROM maven:3.9.9-amazoncorretto-17 AS builder
ARG VERSION=0.0.1-SNAPSHOT

WORKDIR /build/
COPY pom.xml /build/
RUN mvn dependency:go-offline

COPY src /build/src/
RUN mvn clean package -DskipTests

FROM amazoncorretto:17
WORKDIR /app/

COPY --from=builder /build/target/*.jar /app/application.jar
ENTRYPOINT ["java", "-jar", "/app/application.jar"]